# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: black-duck-software.detect-for-tfs.hub.detect.task.BlackDuckDetect@1
  displayName: 'Run Black Duck Detect for your build '
  inputs:
    BlackDuckHubService: bizdevhub
    DetectArguments: |
     --detect.tools=POLARIS \
     --polaris.url=$(polaris.url) \
     --polaris.access.token=$(polaris.token) \
     --polaris. arguments="mvn -f pom.xml clean install"
     --detect.project.name=webgoat-azure-devops \
     --detect.project.version=ci-build-scan \